services:
  # Backend API Service
  - type: web
    name: raph-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: raph-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: raph-redis
          property: connectionString

  # Frontend Service
  - type: web
    name: raph-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: raph-db
    databaseName: raph
    user: raph

redis:
  - name: raph-redis
    ipAllowList: []
